"""Add vehicle compliance and fuel type fields

Revision ID: 09d934ef71d2
Revises: e7f8a9b0c1d2
Create Date: 2026-08-20 16:14:50.618047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09d934ef71d2'
down_revision: Union[str, None] = 'e7f8a9b0c1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE fueltype AS ENUM ('PETROL', 'DIESEL', 'CNG', 'ELECTRIC', 'HYBRID')")
    op.add_column('vehicles', sa.Column('fuel_type', sa.Enum('PETROL', 'DIESEL', 'CNG', 'ELECTRIC', 'HYBRID', name='fueltype'), nullable=True))
    op.add_column('vehicles', sa.Column('engine_number', sa.String(length=100), nullable=True))
    op.add_column('vehicles', sa.Column('chassis_number', sa.String(length=100), nullable=True))
    op.add_column('vehicles', sa.Column('rc_valid_upto', sa.Date(), nullable=True))
    op.add_column('vehicles', sa.Column('puc_number', sa.String(length=100), nullable=True))
    op.add_column('vehicles', sa.Column('puc_valid_upto', sa.Date(), nullable=True))
    op.add_column('vehicles', sa.Column('insurance_policy_number', sa.String(length=100), nullable=True))
    op.add_column('vehicles', sa.Column('insurance_valid_upto', sa.Date(), nullable=True))
    op.add_column('vehicles', sa.Column('permit_type_and_number', sa.String(length=100), nullable=True))
    op.add_column('vehicles', sa.Column('permit_valid_upto', sa.Date(), nullable=True))
    op.add_column('vehicles', sa.Column('fitness_cert_number', sa.String(length=100), nullable=True))
    op.add_column('vehicles', sa.Column('fitness_valid_upto', sa.Date(), nullable=True))
    op.add_column('vehicles', sa.Column('fastag_barcode', sa.String(length=100), nullable=True))
    op.add_column('vehicles', sa.Column('road_tax_paid_upto', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'road_tax_paid_upto')
    op.drop_column('vehicles', 'fastag_barcode')
    op.drop_column('vehicles', 'fitness_valid_upto')
    op.drop_column('vehicles', 'fitness_cert_number')
    op.drop_column('vehicles', 'permit_valid_upto')
    op.drop_column('vehicles', 'permit_type_and_number')
    op.drop_column('vehicles', 'insurance_valid_upto')
    op.drop_column('vehicles', 'insurance_policy_number')
    op.drop_column('vehicles', 'puc_valid_upto')
    op.drop_column('vehicles', 'puc_number')
    op.drop_column('vehicles', 'rc_valid_upto')
    op.drop_column('vehicles', 'chassis_number')
    op.drop_column('vehicles', 'engine_number')
    op.drop_column('vehicles', 'fuel_type')
    op.execute("DROP TYPE fueltype")
    # ### end Alembic commands ###
