"""Add driver fields to users table

Revision ID: 471ff063ad55
Revises: 09d934ef71d2
Create Date: 2026-08-20 17:04:14.218111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '471ff063ad55'
down_revision: Union[str, None] = '09d934ef71d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('aadhaar_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('blood_group', sa.String(length=5), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('dl_expiry', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('dl_type', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('experience_years', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('hub', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('pincode', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('assigned_vehicle_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_assigned_vehicle_id'), 'users', ['assigned_vehicle_id'], unique=False)
    op.create_unique_constraint(None, 'users', ['aadhaar_number'])
    op.create_foreign_key(None, 'users', 'vehicles', ['assigned_vehicle_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_assigned_vehicle_id'), table_name='users')
    op.drop_column('users', 'assigned_vehicle_id')
    op.drop_column('users', 'pincode')
    op.drop_column('users', 'state')
    op.drop_column('users', 'city')
    op.drop_column('users', 'hub')
    op.drop_column('users', 'experience_years')
    op.drop_column('users', 'dl_type')
    op.drop_column('users', 'dl_expiry')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'blood_group')
    op.drop_column('users', 'aadhaar_number')
    # ### end Alembic commands ###
