"""fix_milestone2_schema_issues

Revision ID: 6b552d29ad6f
Revises: 62326dc67c36
Create Date: 2026-08-13 11:03:38.562621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b552d29ad6f'
down_revision: Union[str, None] = '62326dc67c36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'stops',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('clients', 'discount_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
    op.drop_column('documents', 'entity_id')
    op.alter_column('notifications', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_constraint(op.f('push_tokens_created_by_fkey'), 'push_tokens', type_='foreignkey')
    op.drop_constraint(op.f('push_tokens_updated_by_fkey'), 'push_tokens', type_='foreignkey')
    op.drop_column('push_tokens', 'updated_by')
    op.drop_column('push_tokens', 'created_by')
    op.drop_constraint(op.f('trip_location_history_updated_by_fkey'), 'trip_location_history', type_='foreignkey')
    op.drop_constraint(op.f('trip_location_history_created_by_fkey'), 'trip_location_history', type_='foreignkey')
    op.drop_column('trip_location_history', 'deleted_at')
    op.drop_column('trip_location_history', 'is_deleted')
    op.drop_column('trip_location_history', 'updated_at')
    op.drop_column('trip_location_history', 'updated_by')
    op.drop_column('trip_location_history', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_location_history', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('trip_location_history', sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('trip_location_history', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('trip_location_history', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('trip_location_history', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('trip_location_history_created_by_fkey'), 'trip_location_history', 'users', ['created_by'], ['user_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('trip_location_history_updated_by_fkey'), 'trip_location_history', 'users', ['updated_by'], ['user_id'], ondelete='SET NULL')
    op.add_column('push_tokens', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('push_tokens', sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('push_tokens_updated_by_fkey'), 'push_tokens', 'users', ['updated_by'], ['user_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('push_tokens_created_by_fkey'), 'push_tokens', 'users', ['created_by'], ['user_id'], ondelete='SET NULL')
    op.alter_column('notifications', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.add_column('documents', sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False))
    op.alter_column('clients', 'discount_percentage',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('bookings', 'stops',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###
