"""Add complete 18 table schema

Revision ID: 7d93aa68679e
Revises: a1b2c3d4e5f6
Create Date: 2026-08-10 09:47:04.886154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d93aa68679e'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', postgresql.ENUM('ADMIN', 'VENDOR', 'DRIVER', name='userrole', create_type=False), nullable=True),
    sa.Column('action', sa.Enum('LOGIN', 'LOGOUT', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'REJECT', 'SUSPEND', 'ACTIVATE', 'ASSIGN', 'REASSIGN', 'ACCEPT', 'DECLINE', 'TRIP_START', 'TRIP_COMPLETE', 'TRIP_CANCEL', 'INVOICE_ISSUE', 'SETTLEMENT_PAID', 'DOCUMENT_UPLOAD', 'DOCUMENT_APPROVE', 'DOCUMENT_REJECT', name='auditaction'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('driver_duty_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OFF_DUTY', 'ON_DUTY', 'ON_TRIP', 'UNAVAILABLE', name='dutystatus'), nullable=False),
    sa.Column('start_km', sa.Integer(), nullable=True),
    sa.Column('end_km', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_duty_logs_driver_id'), 'driver_duty_logs', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_duty_logs_started_at'), 'driver_duty_logs', ['started_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('PUSH', 'SMS', 'EMAIL', 'IN_APP', name='notificationchannel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'READ', name='notificationstatus'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('pricing_zones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('zone_type', sa.Enum('CITY', 'STATE', 'NATIONAL', name='pricingzonetype'), nullable=False),
    sa.Column('cities', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('push_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_push_tokens_user_id'), 'push_tokens', ['user_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.Enum('HATCHBACK', 'SEDAN', 'SUV', 'PREMIUM_SEDAN', 'TRAVELLER', name='vehicletype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING_APPROVAL', 'ACTIVE', 'INACTIVE', 'SUSPENDED', name='vehiclestatus'), nullable=False),
    sa.Column('registration_number', sa.String(length=20), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('year_of_manufacture', sa.Integer(), nullable=True),
    sa.Column('seating_capacity', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_owner_id'), 'vehicles', ['owner_id'], unique=False)
    op.create_index(op.f('ix_vehicles_registration_number'), 'vehicles', ['registration_number'], unique=True)
    op.create_index(op.f('ix_vehicles_status'), 'vehicles', ['status'], unique=False)
    op.create_index(op.f('ix_vehicles_vehicle_type'), 'vehicles', ['vehicle_type'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('USER', 'VEHICLE', name='documententity'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_url', sa.String(length=512), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size_kb', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='documentstatus'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_expiry_date'), 'documents', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_index(op.f('ix_documents_vehicle_id'), 'documents', ['vehicle_id'], unique=False)
    op.create_table('rate_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('vehicle_type', sa.Enum('HATCHBACK', 'SEDAN', 'SUV', 'PREMIUM_SEDAN', 'TRAVELLER', name='vehicletype'), nullable=False),
    sa.Column('trip_type', sa.Enum('ONE_WAY', 'ROUND_TRIP', 'LOCAL', 'AIRPORT', name='pricingtriptype'), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('base_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('per_km_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('per_minute_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('included_km', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('included_minutes', sa.Integer(), nullable=False),
    sa.Column('extra_km_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('extra_minute_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('night_charge_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('holiday_charge_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vendor_payout_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vendor_flat_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gst_rate_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['pricing_zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_cards_vehicle_type'), 'rate_cards', ['vehicle_type'], unique=False)
    op.create_index(op.f('ix_rate_cards_zone_id'), 'rate_cards', ['zone_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_number', sa.String(length=30), nullable=False),
    sa.Column('source_platform', sa.Enum('MAKEMYTRIP', 'SAVAARI', 'INTERNAL', 'DIRECT', name='bookingsource'), nullable=False),
    sa.Column('external_booking_id', sa.String(length=150), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('rate_card_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_type_required', sa.Enum('HATCHBACK', 'SEDAN', 'SUV', 'PREMIUM_SEDAN', 'TRAVELLER', name='vehicletype'), nullable=False),
    sa.Column('trip_type', sa.Enum('ONE_WAY', 'ROUND_TRIP', 'LOCAL', 'AIRPORT', name='pricingtriptype'), nullable=False),
    sa.Column('pickup_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pickup_address', sa.Text(), nullable=False),
    sa.Column('pickup_latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('pickup_longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('pickup_city', sa.String(length=100), nullable=True),
    sa.Column('destination_address', sa.Text(), nullable=False),
    sa.Column('destination_latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('destination_longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('destination_city', sa.String(length=100), nullable=True),
    sa.Column('estimated_distance_km', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('estimated_duration_min', sa.Integer(), nullable=True),
    sa.Column('stops', sa.JSON(), nullable=False),
    sa.Column('passenger_name', sa.String(length=155), nullable=False),
    sa.Column('passenger_phone', sa.String(length=15), nullable=False),
    sa.Column('passenger_email', sa.String(length=255), nullable=True),
    sa.Column('passenger_count', sa.SmallInteger(), nullable=False),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'VENDOR_ASSIGNED', 'VENDOR_ACCEPTED', 'VENDOR_REJECTED', 'DRIVER_ASSIGNED', 'DRIVER_ACCEPTED', 'DRIVER_REJECTED', 'TRIP_SCHEDULED', 'TRIP_STARTED', 'TRIP_COMPLETED', 'CANCELLED', 'ESCALATED', name='bookingstatus'), nullable=False),
    sa.Column('assigned_vendor_id', sa.Integer(), nullable=True),
    sa.Column('assigned_driver_id', sa.Integer(), nullable=True),
    sa.Column('assigned_vehicle_id', sa.UUID(), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vendor_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('driver_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_driver_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_vendor_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rate_card_id'], ['rate_cards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_number'),
    sa.UniqueConstraint('external_booking_id')
    )
    op.create_index(op.f('ix_bookings_assigned_driver_id'), 'bookings', ['assigned_driver_id'], unique=False)
    op.create_index(op.f('ix_bookings_assigned_vendor_id'), 'bookings', ['assigned_vendor_id'], unique=False)
    op.create_index(op.f('ix_bookings_client_id'), 'bookings', ['client_id'], unique=False)
    op.create_index(op.f('ix_bookings_pickup_datetime'), 'bookings', ['pickup_datetime'], unique=False)
    op.create_index(op.f('ix_bookings_sla_deadline'), 'bookings', ['sla_deadline'], unique=False)
    op.create_index(op.f('ix_bookings_source_platform'), 'bookings', ['source_platform'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_table('booking_assignment_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'TIMEOUT', 'REASSIGNED', name='assignmentstatus'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_assignment_logs_booking_id'), 'booking_assignment_logs', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_assignment_logs_driver_id'), 'booking_assignment_logs', ['driver_id'], unique=False)
    op.create_index(op.f('ix_booking_assignment_logs_status'), 'booking_assignment_logs', ['status'], unique=False)
    op.create_index(op.f('ix_booking_assignment_logs_vendor_id'), 'booking_assignment_logs', ['vendor_id'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_number', sa.String(length=30), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ASSIGNED', 'NAVIGATING_TO_PICKUP', 'REACHED_PICKUP', 'IN_PROGRESS', 'REACHED_DESTINATION', 'COMPLETED', 'CANCELLED', name='tripstatus'), nullable=False),
    sa.Column('pre_duty_checked', sa.Boolean(), nullable=False),
    sa.Column('pre_duty_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vehicle_interior_url', sa.String(length=512), nullable=True),
    sa.Column('vehicle_exterior_url', sa.String(length=512), nullable=True),
    sa.Column('water_bottle_verified', sa.Boolean(), nullable=False),
    sa.Column('cleanliness_verified', sa.Boolean(), nullable=False),
    sa.Column('fuel_level_ok', sa.Boolean(), nullable=False),
    sa.Column('documents_verified', sa.Boolean(), nullable=False),
    sa.Column('start_km', sa.Integer(), nullable=True),
    sa.Column('end_km', sa.Integer(), nullable=True),
    sa.Column('start_location_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('start_location_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('end_location_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('end_location_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('navigating_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reached_pickup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trip_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reached_destination_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_distance_km', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('actual_duration_min', sa.Integer(), nullable=True),
    sa.Column('customer_signature_url', sa.String(length=512), nullable=True),
    sa.Column('driver_remarks', sa.Text(), nullable=True),
    sa.Column('customer_rating', sa.SmallInteger(), nullable=True),
    sa.Column('customer_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendor_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id'),
    sa.UniqueConstraint('trip_number')
    )
    op.create_index(op.f('ix_trips_driver_id'), 'trips', ['driver_id'], unique=False)
    op.create_index(op.f('ix_trips_status'), 'trips', ['status'], unique=False)
    op.create_index(op.f('ix_trips_vehicle_id'), 'trips', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_trips_vendor_id'), 'trips', ['vendor_id'], unique=False)
    op.create_table('escalations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Enum('DRIVER_NO_SHOW', 'VENDOR_NO_RESPONSE', 'TRIP_TIMEOUT', 'CUSTOMER_COMPLAINT', 'VEHICLE_BREAKDOWN', 'OTHER', name='escalationreason'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='escalationstatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalations_booking_id'), 'escalations', ['booking_id'], unique=False)
    op.create_index(op.f('ix_escalations_status'), 'escalations', ['status'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=30), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('rate_card_id', sa.UUID(), nullable=True),
    sa.Column('base_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('extra_distance_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('extra_time_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('night_surcharge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('holiday_surcharge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tolls_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('parking_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('permit_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('other_expenses', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('client_discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gst_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('billed_distance_km', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('billed_duration_min', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'PAID', 'VOID', name='invoicestatus'), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('payment_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rate_card_id'], ['rate_cards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number'),
    sa.UniqueConstraint('trip_id')
    )
    op.create_index(op.f('ix_invoices_booking_id'), 'invoices', ['booking_id'], unique=True)
    op.create_index(op.f('ix_invoices_client_id'), 'invoices', ['client_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('trip_expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('expense_type', sa.Enum('TOLL', 'PARKING', 'PERMIT', 'FUEL', 'MISCELLANEOUS', name='expensetype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('receipt_url', sa.String(length=512), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_expenses_trip_id'), 'trip_expenses', ['trip_id'], unique=False)
    op.create_table('trip_location_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('speed_kmh', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('heading', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_location_history_driver_id'), 'trip_location_history', ['driver_id'], unique=False)
    op.create_index(op.f('ix_trip_location_history_recorded_at'), 'trip_location_history', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_trip_location_history_trip_id'), 'trip_location_history', ['trip_id'], unique=False)
    op.create_table('vendor_settlements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('settlement_number', sa.String(length=30), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('gross_invoice_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vendor_payout_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('vendor_payout_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expense_reimbursement', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_payout', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PAID', 'FAILED', name='settlementstatus'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('payment_mode', sa.String(length=50), nullable=True),
    sa.Column('bank_account_no', sa.String(length=50), nullable=True),
    sa.Column('bank_ifsc', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id'),
    sa.UniqueConstraint('settlement_number')
    )
    op.create_index(op.f('ix_vendor_settlements_status'), 'vendor_settlements', ['status'], unique=False)
    op.create_index(op.f('ix_vendor_settlements_vendor_id'), 'vendor_settlements', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_settlements_vendor_id'), table_name='vendor_settlements')
    op.drop_index(op.f('ix_vendor_settlements_status'), table_name='vendor_settlements')
    op.drop_table('vendor_settlements')
    op.drop_index(op.f('ix_trip_location_history_trip_id'), table_name='trip_location_history')
    op.drop_index(op.f('ix_trip_location_history_recorded_at'), table_name='trip_location_history')
    op.drop_index(op.f('ix_trip_location_history_driver_id'), table_name='trip_location_history')
    op.drop_table('trip_location_history')
    op.drop_index(op.f('ix_trip_expenses_trip_id'), table_name='trip_expenses')
    op.drop_table('trip_expenses')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_client_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_booking_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_escalations_status'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_booking_id'), table_name='escalations')
    op.drop_table('escalations')
    op.drop_index(op.f('ix_trips_vendor_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_vehicle_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_status'), table_name='trips')
    op.drop_index(op.f('ix_trips_driver_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_booking_assignment_logs_vendor_id'), table_name='booking_assignment_logs')
    op.drop_index(op.f('ix_booking_assignment_logs_status'), table_name='booking_assignment_logs')
    op.drop_index(op.f('ix_booking_assignment_logs_driver_id'), table_name='booking_assignment_logs')
    op.drop_index(op.f('ix_booking_assignment_logs_booking_id'), table_name='booking_assignment_logs')
    op.drop_table('booking_assignment_logs')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_source_platform'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_sla_deadline'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_pickup_datetime'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_client_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_assigned_vendor_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_assigned_driver_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_rate_cards_zone_id'), table_name='rate_cards')
    op.drop_index(op.f('ix_rate_cards_vehicle_type'), table_name='rate_cards')
    op.drop_table('rate_cards')
    op.drop_index(op.f('ix_documents_vehicle_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_expiry_date'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_vehicles_vehicle_type'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_status'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_registration_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_owner_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_push_tokens_user_id'), table_name='push_tokens')
    op.drop_table('push_tokens')
    op.drop_table('pricing_zones')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_driver_duty_logs_started_at'), table_name='driver_duty_logs')
    op.drop_index(op.f('ix_driver_duty_logs_driver_id'), table_name='driver_duty_logs')
    op.drop_table('driver_duty_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
